### ISSUE TITLE
Remove run_monitor.sh 

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#108]
Environments are not loading properly into monitor because first run_monitor is running which then calls run_monitor.js and environment variables are not propagated. 

The best thing would be to move run_monitor.sh logic to run_monitor.js

https://github.com/ethereum/source-verify/blob/master/scripts/run_monitor.sh

**Comment by edisinovcic** [comment]
@chriseth @cgewecke is it okay with you guys for this to be done?
Now when everything is running through docker-compose on docker side do we still need script there?

**Comment by cgewecke** [comment]
@edisinovcic Yes, this is fine - the `.sh` was put back in just to introduce a delay when testing locally because all the containers launch in parallel and the monitor was trying to connect to localchain before it launched.

**Comment by chriseth** [comment]
I'm fine with it, too!

**Comment by edisinovcic** [comment]
Awesome, @cgewecke if that's the only change I will test it inside: https://github.com/ethereum/source-verify/pull/91 to check that it all works.

**Comment by edisinovcic** [comment]
Removed in https://github.com/ethereum/source-verify/pull/91 for both server and monitor and ui caching bug also updated.
