### ISSUE TITLE
Monitor only starts with monitoring localchain on testing == true

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#118]
> source-verify@1.0.0 monitor:start /home/app
> node ./scripts/run_monitor.js
> Monitor will attach to test client: http://localchain:8545
> Starting monitor...
> {"name":"Monitor","hostname":"57b585f738fa","pid":18,"level":30,"loc":"[START]","chain":"localhost","block":2,"msg":"Starting monitor for chain","time":"2020-04-06T10:41:30.376Z","v":0}

**Comment by cgewecke** [comment]
This should be fixed now with the env variable changes made to #115. See..

+ https://contractrepostaging.komputing.org/contract/ropsten/0x2bf13B6595e3bdcF0d893481319A9C6954c406d7/
+ https://ropsten.etherscan.io/address/0x2bf13B6595e3bdcF0d893481319A9C6954c406d7
