### ISSUE TITLE
Improve file browser

### ISSUE THREAD

**Issue by chriseth** [ethereum/source-verify#12]
We should offer a better way to browse the source code. It should not be too fancy, but currently, the directory listing is not really nice.

 - improve directory listing
 - display source code with syntax highlighting

At the same time, a raw interface should also be supported, so that people can retrieve the unmodified source or ABI file, for example.

**Comment by edisinovcic** [comment]
Is this covering it: https://contractrepostaging.komputing.org/
Or should we also support something else in the repository?

Directory listing is improved.
There is a syntax highlighting for .sol files
