### ISSUE TITLE
"View the assets in the file explorer" link broken

### ISSUE THREAD

**Issue by ligi** [ethereum/source-verify#128]
see:

![source-verify - Brave_394](https://user-images.githubusercontent.com/111600/79057706-89481d80-7c64-11ea-9872-c70489e9bdac.png)

**Comment by cgewecke** [comment]
This and the problem with the link's root not pointing to the repository subdomain are both fixed on staging with #129

**Address-only submission**
![link_address](https://user-images.githubusercontent.com/7332026/79083463-58f39400-7ce3-11ea-8bce-757ad500f1d2.png)

**Sources submission**
![link_sources](https://user-images.githubusercontent.com/7332026/79083472-6446bf80-7ce3-11ea-8edd-90c127400d5d.png)
