### ISSUE TITLE
Source Verify Remix Plugin bad link

### ISSUE THREAD

**Issue by ryestew** [ethereum/source-verify#148]
The link to this repo in the Source Verify plugin in Remix doesn't have a target=_blank so it tries to open the repo in the iframe in Remix and it fails.

**Comment by edisinovcic** [comment]
This should fix the error: ipfs://QmcpxXUyXV4TYgBErMyVicPuypS2Ts2H7Jdx1sxRHNLbDM

Let me know if the error still persists or if the issue can be closed :)
