### ISSUE TITLE
Monitor E2E test should look for files indexed by chainId

### ISSUE THREAD

**Issue by cgewecke** [ethereum/source-verify#152]
It's failing in CI...

**Comment by edisinovcic** [comment]
I think I fixed it last night?

https://circleci.com/gh/ethereum/source-verify/tree/staging

It was failing as it was trying to access it via name `goerli` but it was saved by id `5` so after that fix it passed.

**Comment by cgewecke** [comment]
Oh great! Sorry. Closing.
