### ISSUE TITLE
use chainId instead of network name

### ISSUE THREAD

**Issue by ligi** [ethereum/source-verify#26]
currently it looks like this:

![image](https://user-images.githubusercontent.com/111600/72196127-6d8b6c00-3416-11ea-8dfa-89e842e8d398.png)

it would be better if chainId's are used here instead of network names. Because if a wallet wants to look up contracts here it then needs a mapping between chainId's and the network names used here. Would be nice to not need this mapping.

**Comment by chriseth** [comment]
Are both of them unique? In that case, we could use both and symlink.

**Comment by ligi** [comment]
chainIDs are unique - with the names I am not 100% sure if there is no collision. So far I have not seen one - but there is no guarantee.

**Comment by ligi** [comment]
sounds great!
3 is Ropsten - see e.g. https://chainid.network

Symlinks are a good idea.
