### ISSUE TITLE
Nicer file upload

### ISSUE THREAD

**Issue by chriseth** [ethereum/source-verify#30]
The look and feel of the file upload page should be improved. We should have a drag and drop area and in general, better input fields.

**Comment by marcgarreau** [comment]
In flight. Got a minimalist react app started with file drag and drop. Nothing being pulled from CDNs. Still wiring it up and touching up the styling, but will hold off on PRs until #31 is merged to establish a baseline.

FYI, don't have any permissions on this repo, so unable to move items on the project kanban board manually.
