### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by cgewecke** [ethereum/source-verify#32]
One way the project could be restructured prior to converting to TS might be:
```
.circleci
Dockerfile
public /
src/
  address-db.js
  injector.js
  monitor.js
  server.js
  utils.js  # Duplicate fns
scripts/
  run.sh
  run_monitor.sh
  run_server.sh
test /
  .. etc ..
```
Some files seem experimental (or incidental) and might be removed / stored away.
+ index.js (?)
+ loop.sh
+ verify.js 

Shell scripts could be aliased to npm scripts
```json
"scripts": {
    "docker:all": "./scripts/run.sh",
    "monitor": "./scripts/run_monitor.sh",
    "server": "./scripts/run_server.sh",
}
```

**Comment by chriseth** [comment]
Sounds good! Yes, index, loop and verify can be removed, although verify could be a stand-alone tool.

**Comment by cgewecke** [comment]
#45
