### ISSUE TITLE
Make "next" branch

### ISSUE THREAD

**Issue by cgewecke** [ethereum/source-verify#33]
It might be useful to have a base branch that new work is targeted at, preserving the current project state until it's safe to merge.

**Comment by chriseth** [comment]
I don't really understand what you want to say with this. In Solidity, for example, we work on one branch per pull request and keep the pull request open until it is safe to merge.

**Comment by cgewecke** [comment]
The changes proposed are extensive - they rewrite most of the files. Was thinking it might be simpler to preserve the repo's current state as a baseline in master and have a branch which accepted a series of smaller PRs targeted at the newer work.

**Comment by cgewecke** [comment]
We discussed this at the Jan 20 meeting and agreed this was not necessary.
