### ISSUE TITLE
UI crashes on error

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#60]
Server:
> Error: Error: Given address "0x00000000000000000000" is not a valid Ethereum address.

UI:
![react-error-crash](https://user-images.githubusercontent.com/16107679/75488553-d9b73480-59b0-11ea-8aa5-becc1bb754e7.png)

**Comment by edisinovcic** [comment]
@cgewecke this is happening when I input wrong contract address inside UI.

**Comment by cgewecke** [comment]
@edisinovcic Weirdly when launching the server locally like this:
```
npm run build:ui && tsc && SERVER_PORT=1234 node ./dist/server.js ./repository
```
...there's no crash - it looks like:
![Screen Shot 2020-02-27 at 1 56 52 PM](https://user-images.githubusercontent.com/7332026/75490596-4dcdea00-5969-11ea-970e-3a6679eeb476.png)

**Comment by edisinovcic** [comment]
This has been resolved by the above commit, tnx @cgewecke! Closing and issue.
