### ISSUE TITLE
Minimal requirements for running a full node

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#93]

**Comment by ligi** [comment]
Background: we need to run a full node to gather the following data:

mapping from address -> creation code
mapping deployed bytecode hash -> address

this issue is to gather information on what hardware do we need to run the node

**Comment by edisinovcic** [comment]
First, we will start with goerli, later other network need to be added: https://github.com/ethereum/source-verify/issues/97

**Comment by tjayrush** [comment]
Hello all. I've been running various types of nodes (archive, tracing, full, Besu, Parity, not Geth) for quite some time. I have two Linux boxes each with 8TB hard drives for each of two archive nodes, and I'm currently running a tracing Besu node on my desktop computer (with a 2TB external hard drive). Anything I can do to help figure out this issue, I'm happy to. Do you have specific questions?

**Comment by edisinovcic** [comment]
Hi @tjayrush 

we are planning on running a modified full node (https://github.com/chriseth/go-ethereum/commit/3f3a599f08bea0843d4080eff64c4328ee819ff0) so we were wondering what minimal hardware requirements we need. 

This is geth fork but if you have feedback on full Besu node that would also be great.

**Comment by edisinovcic** [comment]
This is being discussed and tested here: https://github.com/ethereum/source-verify/issues/97 
Closing this one.
