### ISSUE TITLE
Remix plugin

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#94]
Select a transaction a transaction for debugging (automatically fetch the sources and recompiles it)

**Comment by ligi** [comment]
cc @yann300

**Comment by yann300** [comment]
cool, how do you see the integration?
Having a text input (for the tx hash) in the source verify plugin which will compile and ask the debugger API to start debugging.
or from the debugger to fetch the source (if not already present) using the source verify API?

**Comment by edisinovcic** [comment]
I think currently the second option is more viable. @chriseth what do you think?

**Comment by yann300** [comment]
ok, if you go for the second option, please let us know when the API is added to the plugin so we can use it in the debugger.

**Comment by chriseth** [comment]
Yes, I would also prefer seamless integration with the debugger instead of a standalone entry-point.

**Comment by yann300** [comment]
Do you plan to give a demo of it for the language summit?
We also have now in Remix the "publish to IPFS" from the run tab (for publish automatically to IPFS when a contract is deployed). That with an integration with the debugger can be nice to showcase, we can plan to develop this before the language summit - but probably need 1 week or so for developing it..

**Comment by edisinovcic** [comment]
Hmm, this would definitely be nice to show. So for implementation of the plugin we should aim approx. 15th of this month, so you guys can integrate it afterwards. Is that enough time for you @yann300 ?

**Comment by yann300** [comment]
> Is that enough time for you @yann300 ?
yes I believe so 
cc @lianahus

**Comment by edisinovcic** [comment]
Here is the implementation repo: https://github.com/Shard-Labs/remix-contract-getter
ipfs URL: ipfs://QmXKf5yVg6T67RsfKGjRWhVsu37WETSbboepsKjPoacx6v
